version: "2.0"

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: "shopper"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "65432:5432"

  shopper-api:
    build: .
    depends_on:
      - postgres-db
    environment:
      DB_DRIVER_NAME: "postgresql"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "shopper"
      DB_HOST: "postgres-db"
      DB_PORT: "5432"
