version: "3.8"

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: "shopper"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "65432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  shopper-api:
    build: .
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      DB_DRIVER_NAME: "postgresql"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "shopper"
      DB_HOST: "postgres-db"
      DB_PORT: "5432"
